soulsoft_delivery_asp/ViewModels/EnderecoViewModel.cs
using soulsoft_delivery_asp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace soulsoft_delivery_asp.ViewModels
{
    public class EnderecoViewModel
    {
        public EnderecoApiModel Endereco { get; set; }
        public IEnumerable<TipoEnderecoApiModel> TiposEnderecos { get; set; }
    }
}

soulsoft_delivery_asp/Controllers/EnderecosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using soulsoft_delivery_asp.Models;
using soulsoft_delivery_asp.Services;
using soulsoft_delivery_asp.ViewModels;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace soulsoft_delivery_asp.Controllers
{
    public class EnderecosController : Controller
    {
        const string LocalUrl = "/Endereco/";

        [HttpGet]
        public async Task<IActionResult> CreateOrEdit(int EnderecoId = 0, int ClienteId = 0, string ClientesMessage = "")
        {
            if (ClientesMessage != "")
            {
                ViewData["ClientesMessage"] = ClientesMessage;
            }

            //Instanciando e inicializando o retorno
            EnderecoViewModel EnderecoViewModel = new EnderecoViewModel();
            //Obtendo o Id da Empresa
            int EmpresaId = (int)HttpContext.Session.GetInt32("_empresaId");

            var TiposEnderecosApi = await HttpClienteApi.NewGetAsync<List<TipoEnderecoApiModel>>("/TipoEndereco/Listar/" + EmpresaId);

            if(TiposEnderecosApi != null)
            {
                EnderecoViewModel.TiposEnderecos = TiposEnderecosApi;
            }

            EnderecoApiModel Endereco = new EnderecoApiModel();

            Endereco.Id = EnderecoId;
            Endereco.ClienteId = ClienteId;

            if (EnderecoId != 0)
            {
                var EnderecoApi = await HttpClienteApi.NewGetAsync<List<EnderecoApiModel>>(LocalUrl + "Listar/" + ClienteId);

                if (EnderecoApi != null)
                {
                    Endereco.Id = EnderecoApi[0].Id;
                    Endereco.Bairro = EnderecoApi[0].Bairro;
                    Endereco.Quadra = EnderecoApi[0].Quadra;
                    Endereco.Numero = EnderecoApi[0].Numero;
                    Endereco.Lote = EnderecoApi[0].Lote;
                    Endereco.Cep = EnderecoApi[0].Cep;
                    Endereco.Rua = EnderecoApi[0].Rua;
                    Endereco.Complemento = EnderecoApi[0].Complemento;
                    Endereco.ClienteId = EnderecoApi[0].ClienteId;
                    Endereco.TipoEnderecoId = EnderecoApi[0].TipoEnderecoId;
                }
            }

            EnderecoViewModel.Endereco = Endereco;

            return View(EnderecoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrEdit(EnderecoViewModel EnderecoViewModel)
        {
            int EmpresaId = (int)HttpContext.Session.GetInt32("_empresaId");

            if (ModelState.IsValid)
            {
                EnderecoApiModel Endereco = new EnderecoApiModel();
                Endereco = EnderecoViewModel.Endereco;
                Endereco.Ativo = true;

                if (Endereco.Id == 0)
                {
                    var Response = await HttpClienteApi.NewPostAsync<object>(LocalUrl, Endereco);
                    if(Response != null)
                    {
                        return Redirect($"/Clientes/CreateOrEdit?Id={Endereco.ClienteId}&ClientesMessage=Endereço Cadastrado com Sucesso!");
                    }

                }
                else
                {
                    var Response = await HttpClienteApi.NewPutAsync<object>(LocalUrl, Endereco);
                    if (Response != null)
                    {
                        return Redirect($"/Clientes/CreateOrEdit?Id={Endereco.ClienteId}&ClientesMessage=Endereço Alterado com Sucesso!");
                    }
                }
            }

            return View(EnderecoViewModel);
        }

        //[HttpGet]
        //public IActionResult Delete(int EnderecoId)
        //{
        //    HttpResponseMessage response = _httpClient.DeleteAsync($"Endereco/{EnderecoId}").Result;
        //    if (response.IsSuccessStatusCode)
        //    {
        //        var responseString = response.Content.ReadAsStringAsync().Result;
        //        dynamic responseJson = JsonConvert.DeserializeObject(responseString);
        //        if (responseJson.status == "Sucesso")
        //        {
        //            return Redirect("/Clientes/Index?ClientesMessage=Cliente removido com Sucesso.");
        //        }
        //    }
        //    return RedirectToAction("Index");
        //}
    }
}

soulsoft_delivery_asp/Views/Enderecos/CreateOrEdit.cshtml
@model soulsoft_delivery_asp.ViewModels.EnderecoViewModel

@{
    ViewData["breadcrumb"] = "Clientes";
    ViewData["breadcrumb_url"] = "/Clientes/Index";
    ViewData["title"] = "Cadastrar";
}

@if (ViewData["ClientesMessage"] != null)
{
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2 mr-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill" /></svg>
        <div>
            @ViewData["ClientesMessage"]
        </div>

    </div>
}

<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- jquery validation -->
        <div class="card card-secundary">
            <div class="card-header">
                <h3 class="card-title">Dados do Endereço</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <form method="post" asp-controller="Enderecos" asp-action="CreateOrEdit">
                <div class="card-body">

                    <input type="hidden" asp-for="Endereco.Id">
                    <input type="hidden" asp-for="Endereco.ClienteId">

                    <div class="form-group">
                        <label for="tipo_usuario_id">Tipo de Usuário</label>
                        <select asp-for="Endereco.TipoEnderecoId" class="form-control" id="TipoUsuarissoId">
                            @foreach (var TipoEndereco in Model.TiposEnderecos)
                            {
                                <option value="@TipoEndereco.Id">@Html.DisplayFor(modelItem => TipoEndereco.Nome)</option>
                            }
                        </select>
                        <span asp-validation-for="Endereco.TipoEnderecoId" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label for="senha">Bairro*</label>
                        <input type="text" asp-for="Endereco.Bairro" class="form-control" placeholder="Digite o Bairro">
                        <span asp-validation-for="Endereco.Bairro" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="Cep">Cep</label>
                        <input type="text" asp-for="Endereco.Cep" class="form-control" placeholder="Digite o CEP">
                        <span asp-validation-for="Endereco.Cep" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="Rua">Rua</label>
                        <input type="text" asp-for="Endereco.Rua" class="form-control" placeholder="Digite a Rua">
                        <span asp-validation-for="Endereco.Rua" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="Numero">Número</label>
                                <input type="text" asp-for="Endereco.Numero" class="form-control" placeholder="Digite o Número">
                                <span asp-validation-for="Endereco.Numero" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="Quadra">Quadra</label>
                                <input type="text" asp-for="Endereco.Quadra" class="form-control" placeholder="Digite a Quadra">
                                <span asp-validation-for="Endereco.Quadra" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="Lote">Lote</label>
                                <input type="text" asp-for="Endereco.Lote" class="form-control" placeholder="Digite o Lote">
                                <span asp-validation-for="Endereco.Lote" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Complemento">Complemento</label>
                        <input type="text" asp-for="Endereco.Complemento" class="form-control" placeholder="Digite o Complemento">
                        <span asp-validation-for="Endereco.Complemento" class="text-danger"></span>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <a asp-controller="Clientes" asp-action="Index" class="btn btn-danger">Cancelar</a>
                </div>
            </form>
        </div>
        <!-- /.card -->
    </div>
    <!--/.col (left) -->
</div>
<!-- /.row -->

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}